[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ag-ui-claude-sdk>=0.1.5",
    "ag-ui-protocol>=0.1.19",
    "anthropic>=0.121.0",
    "claude-agent-sdk>=0.2.137",
    "fastapi>=0.141.1",
    "python-dotenv>=1.2.2",
    "uvicorn>=0.52.2",
]
